services:
  saleor-app-payment-stripe:
    container_name: saleor-app-payment-stripe
    build:
      dockerfile: Dockerfile
      args:
        APP_DEBUG: ${APP_DEBUG}
        SECRET_KEY: ${SECRET_KEY}
    environment:
      APP_DEBUG: ${APP_DEBUG}
      SECRET_KEY: ${SECRET_KEY}
    restart: always
    ports:
      - 5000:3000
    # networks:
    #   - saleor_network
# networks:
#   saleor_network:
#     external: false
