services:
  saleor-app-payment-stripe:
    container_name: saleor-app-payment-stripe
    build:
      dockerfile: Dockerfile
      args:
        APP_DEBUG: ${APP_DEBUG}
        SECRET_KEY: ${SECRET_KEY}
    environment:
      APP_DEBUG: ${APP_DEBUG}
      SECRET_KEY: ${SECRET_KEY}
    restart: always
    ports:
      - 3000:3000
    # networks:
    #   - saleor_network

  # Add more containers below (nginx, postgres, etc.)

# networks:
#   saleor_network:
#     external: false
